<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.3.1';
$moduleRevision = 'f6098d6ec939899df9fb8e18bf5986781a05eceb';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/';