<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */
require_once __DIR__ . '/loaderPM.php';
$moduleVersion = '1.4.0';
$moduleRevision = 'daea89cd2ebf0d5b94fba86a614bd9cf714deb34';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Client_Area_Popup_For_WHMCS';