<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.1.6';
$moduleRevision = '4c55134ddbdb8b26d9ea5fbbc31daca1edd820ed';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Product_Cross-Selling_For_WHMCS';